- hosts: all
  user: pratigya
  become: True
  tasks:
    - name: Install 
      apt:
       name: apache2
       state: latest
    - name: Make sure apache2 service is running
      service:
        name: apache2
        state: started
        enabled: True
    - name: Copy index.html file to server
      tags: apache2
      copy:
        src:  ../files/index.html
        dest: /var/www/html/index.html
        mode: 0644
        owner: www-data
        group: www-data 

    - name: install unzip
      apt:
        name: unzip

    - name: install terraform
      unarchive: 
         src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
         dest: /usr/local/bin
         remote_src: yes
         mode: 0755
         owner: root
         group: root
 
     
 
