---
-  hosts: all
   user: pratigya
   collections:
    - jfrog.platform
   become: yes
   tasks: 
      - name: run container
        docker:
           insecure_registry: true
           #registry_url: https://webappartifactory.jfrog.io/artifactory/docker/

           image: webappartifactory.jfrog.io/docker-local/mathapp-production:latest
           state: reloaded
           pull: always
           ports:
              - "8020:8020"

  
    
